website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from website.forms import RegistrationForm

from website.forms import LoginForm
from . import db
from .models import User
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint("auth", __name__)


@auth.route("/", methods=['GET', 'POST'])
def landing():
    form = LoginForm()
    # if request.method == 'post':
    #     return redirect('login') 
    return render_template("landing.html", user=current_user, form=form)


@auth.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated: 
        return redirect(url_for('views.home'))
    
    form = LoginForm()

    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data.lower(), active=1).first()
        if user and check_password_hash(user.password, form.password.data) :
            login_user(user, remember=True)
            flash("Logged in!", category='success')
            next_page = request.args.get('next') 
            return redirect(next_page) if next_page else redirect(url_for('views.home')) 
        else:
            flash('Username and/or Password incorrect.', category='error') 
    return render_template("login.html", user=current_user, form=form) 


@auth.route("/sign-up", methods=['GET', 'POST'])
def sign_up():
    if current_user.is_authenticated: 
        return redirect(url_for('views.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(
                email=form.email.data.lower(), 
                username=form.username.data, 
                password=generate_password_hash(form.password.data, 
                method='sha256')
            )
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user, remember=True)
        flash(f"Account created for {form.username.data}!", category="success")
        return redirect(url_for('auth.login'))

    return render_template("signup.html", user=current_user, form=form)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.landing"))


website/views.py
import os
import secrets
from flask import current_app, Blueprint, render_template, request, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user, logout_user
from sqlalchemy import select, or_
from .models import Post, User, Comment, Like
from .forms import (LoginForm, RegistrationForm, 
                    UpdateEmailForm, UpdateProfilePic, 
                    RequestResetForm, ResetPasswordForm, UpdateUsernameForm)
from .utils import save_picture
from . import db
from PIL import Image

views = Blueprint("views", __name__)


@views.route("/home")
@login_required 
def home():
    page = request.args.get('page', 1, type=int)

    # query to filter only active user IDs
    is_active_ids = db.session.query(User.id).filter_by(active=1)

    posts = Post.query\
                .filter(Post.author.in_(is_active_ids))\
                .order_by(Post.date_created.desc())\
                .paginate(page=page, per_page=10) 

    # list of active user IDs for use in posts_div view
    comment_id_list = [id for tup in is_active_ids.all() for id in tup]

    return render_template("home.html", user=current_user, posts=posts, id_list=comment_id_list)

@views.route("/profile", methods=['GET', 'POST'])
@login_required
def profile():
    # Email, username, password, profile pic forms 
    update_em_form = UpdateEmailForm()
    update_un_form = UpdateUsernameForm()
    update_pp_form = UpdateProfilePic() 


    if update_pp_form.validate_on_submit():
        if update_pp_form.profile_pic.data:
            picture_file = save_picture(update_pp_form.profile_pic.data) 
            current_user.image_file = picture_file 
        db.session.commit()

        return redirect(url_for('views.profile'))
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file) 
    return render_template("profile.html", image_file=image_file, 
                            update_em_form=update_em_form,
                            update_pp_form=update_pp_form,
                            update_un_form=update_un_form) 


@views.route("/create-post", methods=['GET', 'POST'])
@login_required
def create_post():
    if request.method == "POST":
        text = request.form.get('text')

        if not text:
            flash('Post cannot be empty', category='error')
        else:
            post = Post(text=text, author=current_user.id)
            db.session.add(post)
            db.session.commit()
            flash('Post created!', category='success')
            return redirect(url_for('views.home'))

    return render_template('create_post.html', user=current_user)


@views.route("/delete-post/<id>", methods=['POST'])
@login_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first()

    if not post:
        flash("Post does not exist.", category='error')
    elif current_user.id != post.author:
        flash('You do not have permission to delete this post.', \
              category='error')
    else:
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted.', category='success')

    return redirect(url_for('views.home'))


@views.route("/posts/<string:username>")
@login_required
def posts(username):
    user = User.query.filter_by(username=username, active=True).first()

    if not user:
        flash('No user with that username exists.', category='error')
        return redirect(url_for('views.home'))

    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(author=user.id)\
                .order_by(Post.date_created.desc())\
                .paginate(page=page, per_page=10)
    is_active_ids = db.session.query(User.id).filter_by(active=1)
    comment_id_list = [id for tup in is_active_ids.all() for id in tup]

    return render_template("posts.html", \
            user=current_user, posts=posts, username=username, id_list=comment_id_list)

@views.route("/create-comment/<post_id>", methods=['POST'])
@login_required
def create_comment(post_id):
    text = request.form.get('text')

    if not text:
        flash('Comment cannot be empty.', category='error')
    else:
        post = Post.query.filter_by(id=post_id)
        if post:
            comment = Comment(
                text=text, author=current_user.id, post_id=post_id)
            db.session.add(comment)
            db.session.commit()
        else:
            flash('Post does not exist.', category='error')

    return redirect(url_for('views.home'))


@views.route("/delete-comment/<comment_id>")
@login_required
def delete_comment(comment_id):
    comment = Comment.query.filter_by(id=comment_id).first()
    if not comment:
        flash('Comment does not exist.', category='error')
    elif current_user.id != comment.author and current_user.id != comment.post.author:
        flash('You do not have permission to delete this comment.', \
              category='error')
    else:
        db.session.delete(comment)
        db.session.commit()
    return redirect(url_for('views.home'))

@views.route("/delete-account", methods=['POST', 'GET'])
def delete_account():
    current_user.active = 0
    current_user.email = current_user.email + '_deleted'
    db.session.commit()
    logout_user()
    flash("Your account has been deleted.", category='info')
    return redirect(url_for('auth.landing'))


@views.route("/like-post/<post_id>", methods=['POST'])
@login_required
def like(post_id):
    post = Post.query.filter_by(id=post_id).first()
    like = Like.query.filter_by(
        author=current_user.id, post_id=post_id).first()
    if not post:
        return jsonify({'error': 'Post does not exist.'}, 400)
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        like = Like(author=current_user.id, post_id=post_id)
        db.session.add(like)
        db.session.commit()

    return jsonify({"likes": len(post.likes), "liked": current_user.id in map(lambda x: x.author, post.likes)})

@views.route("/update-email", methods=['POST']) 
@login_required 
def update_email():
    update_em_form = UpdateEmailForm() 
    if update_em_form.validate_on_submit():
        user = User.query.get(current_user.id) 
        user.email = update_em_form.email.data 
        db.session.add(user)
        db.session.commit()
        flash("Email updated successfully", category='success')  
    return redirect(url_for('views.profile'))    

@views.route("/update-username", methods=['POST']) 
@login_required 
def update_username():
    update_un_form = UpdateUsernameForm() 
    if update_un_form.validate_on_submit():
        user = User.query.get(current_user.id) 
        user.username = update_un_form.username.data 
        db.session.add(user)
        db.session.commit()
        flash("Username updated successfully", category='success')  
    return redirect(url_for('views.profile'))

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link rel=icon href="{{ url_for('static', filename='favicon.ico') }}"" sizes="16x16">
    <link rel="stylesheet" href="../static/styles.css">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

    <!-- Navbar  -->
    <nav class="navbar navbar-expand-lg navbar-dark nav-bg">   
      <div class="container-fluid">
        <div class="navbar-brand nav-link">
          BloggoSoft
        </div>
        <!-- Button for navbar collapse  -->
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Collapsible portion of navbar -->
        <div class="collapse navbar-collapse" id="navbar">
          {% if current_user.is_authenticated %} 
            <ul class="navbar-nav me-auto mt-2">
              <li>
                <a class="nav-link" href="{{ url_for('views.create_post') }}">Create Post</a>
              </li>
              <li>
                <a class="nav-link" href="{{ url_for('views.profile') }}">Profile</a>
              </li>
            </ul>
            <ul class="navbar-nav ms-auto mt-2">
              <li>
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
              </li>
            </ul>
          {% else %} 
            <ul class="navbar-nav me-auto mt-2">
            </ul>
            <ul class="navbar-nav ms-auto mt-2">
              <li>
                <a class="btn btn-outline-light mx-2" href="{{ url_for('auth.login') }}">Login</a>
              </li>
              <li>
                <a class="btn btn-light" href="{{ url_for('auth.sign_up') }}">Register</a>
              </li>
            </ul>
          {% endif %} 
        </div>
      </div>
    </nav>
    
    <!-- Flashed messages  -->
    {% with messages = get_flashed_messages(with_categories=true) %} 
      {% if messages %} 
        {% for category, message in messages %} 
          {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
          {% else %}
            <div class="alert alert-success alter-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
          {% endif %} 
        {% endfor %} 
      {% endif %} 
    {% endwith %}
    
    <!-- Content for all pages -->
    {% block content %} {% endblock %}
    
    <!-- Bootstrap script  -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>

    <!-- Site script for likes and modals  -->
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js')}}"
    ></script>
  </body>
</html>

website/templates/create_post.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<div class="container">
<h1 class="mt-3">Create a Post</h1>

<form method="POST">
  <textarea name="text" id="text" class="form-control"></textarea>
  <br />
  <div align="center">
    <button type="submit" class="btn btn-lg btn-primary">Post</button>
  </div>
</form>
<br />
<div align="center">
  <!-- <a href="/home"> -->
  <a href="{{ url_for('views.home') }}">
    <button type="button" class="btn btn-lg btn-secondary">Back</button>
  </a>
</div>
</div>
{% endblock %}

website/templates/home.html
{% extends "posts_div.html" %} 

{% block title %}Home{% endblock %}


website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<div class="container">
  <h3 class="my-3">Login</h3>

  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <div class="form-floating mb-3">  
      {% if form.email.errors %} 
        {{ form.email(class="form-control is-invalid", placeholder="name@example.com") }}
        {% for error in form.email.errors %}
          <div class="invalid-feedback">
            <span>{{ error }}</span>
          </div>
        {% endfor %} 
      {% else %} 
        {{ form.email(class="form-control", id="floatingInput", placeholder="name@example.com") }}
      {% endif %} 
      {{ form.email.label(for="floatingInput") }}
    </div>
    <div class="form-floating mb-3">
      {% if form.password.errors %} 
        {{ form.password(class="form-control is-invalid", placeholder="Password") }}
        {% for error in form.password.errors %} 
          <div class="invalid-feedback">
            <span>{{ error }}</span>
          </div>
        {% endfor %} 
      {% else %}
        {{ form.password(class="form-control", id="floatingPassword", placeholder="Password")}}
      {% endif %} 
      {{ form.password.label(for="floatingInput") }}
      {{ form.submit(class="w-100 mt-3 btn btn-lg btn-primary") }}
    </div>
    <div class="pt-3">
      <small class="text-muted">
        Forgot your password? 
        <a href="#" class="ml-2" data-bs-toggle="modal" data-bs-target="#pwResetModal">
          Reset it
        </a>
      </small>
    </div>
  </form>
</div>
{% endblock %}

website/templates/posts.html
{% extends "posts_div.html" %} 

{% block title %}
  {{username}}'s Posts
{% endblock title %} 

{% block header %} <h1 class="mt-3">Posts by {{username}} ({{ posts.total }})</h1> {% endblock header %} 

<!-- TODO: fix pagination to point 2nd and later pages to user's posts, not home -->

{% block footer %}
<div >
  <a href="/home"><button type="button" class="btn btn-primary btn-lg">Back</button></a>
</div>
{% endblock footer %}

website/templates/profile.html
{% extends "base.html" %} 

{% block add_head %} 

<!-- TODO: bring over stylesheet, get header img, update 
     models with image
-->
<link rel="stylesheet" href="../static/profile.css"> 

{% endblock add_head %} 

{% block content %} 

<div class="pb-5 pt-3">
  <!-- Top section -- background, avatar, username -->
  <div class="container">
    <div class="row align-items-center justify-content-between">
      <div class="col">
        <!-- Background -->
        <div
          class="pt-16 rounded-top-md"
          style="
            background: url(../static/gradientbg.png)
            no-repeat;
            background-size: cover;
          "
        ></div>
        <!-- Avatar and username -->
        <div class="d-flex align-items-end justify-content-between bg-white px-4 pt-2 pb-4 rounded-none rounded-bottom-md shadow-sm">
          <div class="d-flex align-items-center">
            <div class="me-2 position-relative d-flex justify-content-end align-items-end mt-n5">
              <img
                src="{{ image_file }}"
                class="avatar-xl rounded-circle border border-4 border-white"
                alt=""
                style="background-color: #fff"
              />
            </div>
            <div class="lh-1">
              <h2 class="mb-0">{{current_user.email}}</h2>
              <p class="mb-0 d-block">@{{current_user.username}}</p>
            </div>
          </div>
          <div>
          <!-- Button (not shown on mobile) -->
            <a href="/create_post"
              class="btn btn-outline-primary btn-sm rounded-pill d-none d-md-block"
              >Create Post
            </a>
          </div>
        </div>
      </div>
    </div>
</div>

<!-- Update section  -->
<section class="container w-75">
  <h1 class="h3 mb-3 mt-3 fw-normal">Account Info</h1>
  
  <!-- Email Update -->
  <div class="d-flex mb-3 align-items-center justify-content-between w-50">
    <div class="row w-50 mx-2">
      <p class="lead justify-content-start mb-1">Email: </p>
      <p class="text-muted">{{ current_user.email }}</p>
    </div>
    <div>
      <a href="#" data-bs-toggle="modal" data-bs-target="#emailChangeModal">
        <button class="btn btn-outline-primary btn-sm rounded-pill">Change</button>
      </a>
    </div>
  </div>
  <hr class="w-50">
  
  <!-- Username Update -->
  <div class="d-flex mb-3 align-items-center justify-content-between w-50">
    <div class="row w-50 mx-2">
      <p class="lead justify-content-start mb-1">Username: </p>
      <p class="text-muted">{{ current_user.username }}</p>
    </div>
    <div>
      <a href="#" data-bs-toggle="modal" data-bs-target="#usernameChangeModal">
        <button class="btn btn-outline-primary btn-sm rounded-pill">Change</button>
      </a>
    </div>
  </div>
  <hr class="w-50">

  <!-- Password Update -->
  <div class="d-flex mb-3 align-items-center justify-content-between w-50">
    <div class="row w-50 mx-2">
      <p class="lead justify-content-start mb-1">Password: </p>
      <p class="text-muted">**********</p>
    </div>
    <div>
      <a href="#"><button class="btn btn-outline-primary btn-sm rounded-pill">Change</button></a>
    </div>
  </div>
  <hr class="w-50">

  <!-- Profile Pic Update -->
<div class="d-flex mb-3 align-items-center justify-content-between w-50">
  <form method="POST" action="" name="updateProfPic" enctype="multipart/form-data" class="w-100">
    {{ update_pp_form.hidden_tag() }}
    <div class="row w-50 mx-2">
      <div class="form-group">
        <p class="lead justify-content-start mb-1">Update Profile Pic: </p> 
          <div class="justify-content-end">
          <label for="profile_pic">
            {{ update_pp_form.profile_pic }}
            Browse
          </label>
          <input class="btn btn-outline-primary btn-sm rounded-pill" id="submit" name="submit" type="submit" value="Submit">
          </div>
      </div>
      <div>
        {% if update_pp_form.profile_pic.errors %} 
          {% for error in update_pp_form.profile_pic.errors %} 
            <span class="text-danger">{{ error }}</span>
          {% endfor %} 
        {% endif %}
        <!-- {{ update_pp_form.submit(class="btn btn-outline-info rounded-pill") }} -->
      </div>
    </div>
  </form>
</div>
<hr class="w-50">

  <!-- Account Deletion -->
  <div class="d-flex mb-3 align-items-center justify-content-between w-50">
    <div class="row w-50 mx-2">
      <p class="lead justify-content-start mb-1" style="color: red;">Delete Account: </p>
      <p class="small" style="color: red;">Warning! This cannot be undone.</p>
    </div>
    <a href="#" data-bs-toggle="modal" data-bs-target="#deleteAccountModal">
      <button type="button" class="btn btn-sm btn-outline-danger rounded-pill">Delete</button>
    </a>
  </div>
  <hr class="w-50">
</section>
</div>

<!-- Change Email Modal -->
<!-- TODO: Find way to validate em on page -->
<div class="modal fade" id="emailChangeModal" tabindex="-1" aria-labelledby="emailChangeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="emailChangeModalLabel">Update Email Address</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        New e-mail address:
        <br>
        <form action="{{ url_for('views.update_email') }}" method="POST"> 
          {{ update_em_form.hidden_tag() }}
          {{ update_em_form.email(class="mb-2") }}

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary rounded-pill" data-bs-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary rounded-pill">Update Email</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Change Username Modal -->
<div class="modal fade" id="usernameChangeModal" tabindex="-1" aria-labelledby="usernameChangeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="usernameChangeModalLabel">Update Username</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        New username:
        <br>
        <form action="{{ url_for('views.update_username') }}" method="POST"> 
          {{ update_un_form.hidden_tag() }}
          {{ update_un_form.username(class="mb-2") }}
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary rounded-pill" data-bs-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary rounded-pill">Update Username</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Delete Account Modal -->
<div class="modal fade" id="deleteAccountModal" tabindex="-1" aria-labelledby="deleteAccountModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteAccountModalLabel">Delete Account</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="mb-3">Are you sure you want to delete your account?  This cannot be undone.</div>
          <form action="{{ url_for('views.delete_account') }}" method="POST">
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary rounded-pill" data-bs-dismiss="modal">Cancel</button>
              <button type="submit" class="btn btn-danger rounded-pill">Delete Account</button>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>

  
{% endblock content %} 

website/templates/signup.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<div class="container">
<h3 class="mb-3">Sign Up</h3>
<form method="POST">

  {{ form.hidden_tag() }}

  <div class="form-floating">
    {% if form.email.errors %} 
      {{ form.email(class="form-control is-invalid", placeholder="name@example.com") }}
      {% for error in form.email.errors %} 
        <div class="invalid-feedback">
          <span>{{ error }}</span>
        </div>
      {% endfor %} 
    {% else %} 
      {{ form.email(class="form-control", id="floatingInput", placeholder="name@example.com") }} 
    {% endif %} 
    {{ form.email.label(for="floatingInput") }}
  </div>
  <div class="form-floating">
    {% if form.username.errors %} 
      {{ form.username(class="form-control is-invalid", placeholder="Username") }}
      {% for error in form.username.errors %} 
        <div class="invalid-feedback">
          <span>{{ error }}</span>
        </div>
      {% endfor %} 
    {% else %} 
      {{ form.username(class="form-control", id="floatingInput", placeholder="Username") }} 
    {% endif %}
    {{ form.username.label(for="floatingInput") }}
  </div>
  <div class="form-floating">
    {% if form.password.errors %} 
      {{ form.password(class="form-control is-invalid", placeholder="Password") }}
      {% for error in form.password.errors %} 
        <div class="invalid-feedback">
          <span>{{ error }}</span>
        </div>
      {% endfor %} 
    {% else %} 
      {{ form.password(class="form-control", id="floatingPassword", placeholder="Password")}}
    {% endif %} 
    {{ form.password.label(for="floatingInput") }}
  </div>

  {{ form.submit(class="w-100 btn btn-lg btn-primary") }}
  
  <div class="border-top pt-3">
      <small class="text-muted">
          Have an account? <a class="ml-2" href="{{ url_for('auth.login') }}">Sign in</a>
      </small>
  </div>

  <p class="mt-3 mb-3 text-muted">&copy; BloggoSoft</p>

  
</form>
</div>
{% endblock %}